name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 👇 Build steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        
      - name: Install dependencies
        run: npm update ci frozen-lockfile --non-interactive

      - name: Build
        run: npm run build

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
        path: build
       

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deplo
        id: deployment
        uses: actions/deploy-pages@v1